# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428338a5e54e4a24d23c9db673a4ae010ca1b6d3cdd6b0d13ec62018681d2f4721bf05d500ff1e5f4fd198fbce5e2dffced831ba4d1d92bd52d17c418c7f0f85

test:
  secret_key_base: d274ebfffb237e04874979a99bc6a0a1950b52e80bbff2c17eff8d3d1590dfc76f1e77f93a27991e64e59ffcec75b78fe8c366002cb14b3cd9c0b809e2603f71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
